import type { Metadata } from "next";
// Import Nunito_Sans instead of Geist
import { Nunito_Sans } from "next/font/google";
import "./globals.css";

// Configure Nunito Sans
const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans", // Use a new variable name
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
